name: rosary_app
description: Aplicativo de rosário com funcionalidades inovadoras.

# Versão do SDK Flutter
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependência para salvar e carregar preferências locais
  shared_preferences: ^2.0.6

  # Outras dependências necessárias para o projeto
  provider: ^6.1.2
  audioplayers: ^6.0.0
  video_player: ^2.1.15
  cached_network_image: ^3.1.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cruz_light.png
    - assets/cruz_dark.png
    - assets/santinho.png

  # Adicione outras imagens e vídeos aqui
  # - assets/other_image.png
  # - assets/video.mp4